# Generated by Django 5.0 on 2023-12-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='не начато', max_length=300, verbose_name='Статус'),
        ),
    ]
