# Generated by Django 5.0 on 2023-12-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_todo_is_complete_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название задания')),
                ('status', models.CharField(default='не начато', max_length=300, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
