# Generated by Django 5.0 on 2023-12-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_todohistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todohistory',
            options={'verbose_name': 'archive Задание', 'verbose_name_plural': 'История заданий'},
        ),
    ]
